server:
  port: 3333

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: person-service
        uri: lb://person-service
        predicates:
        - Path=/person/**
      - id: education-service
        uri: lb://education-service
        predicates:
        - Path=/education/**